In [4]:
#1.a.i
import numpy as np
matrix = np.array 
a = np.array ([[26,21,2],
               [1,2,1]])
b = np.array ([[2,0,2],
               [5,5,7]])
print ("Matrix_A:\n",a)
print ("Matrix_B:\n",b)

Matrix_A:
 [[26 21  2]
 [ 1  2  1]]
Matrix_B:
 [[2 0 2]
 [5 5 7]]


In [6]:
#2.a
c = (a+b)
print ("Matrix_C:\n",c)

Matrix_C:
 [[28 21  4]
 [ 6  7  8]]


In [8]:
#3.a
d = a*2
print ("Matrix_D:\n",d)

Matrix_D:
 [[52 42  4]
 [ 2  4  2]]


In [9]:
#4.a
transposed_b = b.T
print ("Matrix_E:\n", transposed_b)

Matrix_E:
 [[2 5]
 [0 5]
 [2 7]]


In [10]:
#5.a
f = np.dot(c,transposed_b)
print ("Matrix_F:\n",f)

Matrix_F:
 [[ 64 273]
 [ 28 121]]


In [11]:
#6.a 
C = np.sum (c)
print ("Sum_Matrix_C:\n",C)

Sum_Matrix_C:
 74


In [12]:
#7.a
G = np.zeros((2,3))
print ("Matrix_G:\n",G)

Matrix_G:
 [[0. 0. 0.]
 [0. 0. 0.]]
